EStore/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

from django.conf.urls.static import static
from django.conf import settings

from rest_framework import routers
from store import views

router = routers.DefaultRouter()
router.register(r'products', views.ProductViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
    path('', include('customer.urls')),
    path('', include('cart.urls')),
    path('', include('dashboard.urls')),
    path('', include('storereport.urls')),
    path('', include('analysis.urls')),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('api/', include(router.urls)),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from cart import views


app_name = 'cart'
urlpatterns = [
    path('cart/', views.cart_detail, name='cart_detail'),
    path('buy-now/<int:product_id>/', views.buy_now, name='buy_now'),
    path('cart-remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('checkout/', views.checkout, name='checkout'),
]

customer/urls.py
from django.urls import path
from customer import views


app_name = 'customer'
urlpatterns = [
    path('login/', views.customer_login_signup, name='login'),
    path('login-2/', views.customer_login_signup_2, name='login_2'),
    path('logout/', views.customer_logout, name='logout'),
    path('my-account/', views.my_account, name='my_account'),
]

store/urls.py
from django.urls import path
from store import views


app_name = 'store'
urlpatterns = [
    path('', views.index, name='index'),
    path('subcategory/<int:pk>/', views.subcategory, name='subcategory'),
    path('contact/', views.contact, name='contact'),
    path('user/', views.demo_user, name='user'),
    path('logout-user/', views.logout_user, name='logout_user'),
    path('products-service/', views.products_service, name='products_service'),
    path('products-service/<int:pk>/', views.product_service, name='product_service'),
    path('search/', views.search, name='search'),
    path('product/<int:pk>/', views.product_detail, name='product_detail'),
]

cart/models.py
from django.db import models
from store.models import Product


# Create your models here.
class Order(models.Model):
    username = models.EmailField(null=False)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    phone = models.CharField(max_length=20, null=True)
    address = models.CharField(max_length=500, unique=False)
    total = models.DecimalField(max_digits=10, decimal_places=2)
    status = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return f'Order {self.id}'


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, related_name='order_items', on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return str(self.id)

store/models.py
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField
from datetime import datetime
from django.contrib.auth.models import User
from django.utils import timezone


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=150, unique=True)

    def __str__(self):
        return self.name


class SubCategory(models.Model):
    category = models.ForeignKey(Category, on_delete=models.PROTECT)
    name = models.CharField(max_length=150, unique=True)
    image = models.ImageField(upload_to='store/images', default='store/images/default.png')

    def __str__(self):
        return self.name


class Product(models.Model):
    subcategory = models.ForeignKey(SubCategory, on_delete=models.PROTECT, related_name='products')
    name = models.CharField(max_length=250)
    price = models.FloatField(default=0.0)
    price_origin = models.FloatField(null=True)
    image = models.ImageField(upload_to='store/images', default='store/images/default.png')
    content = RichTextUploadingField(blank=True, null=True)
    public_day = models.DateTimeField(default=timezone.now)
    viewed = models.IntegerField(default=0)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['-public_day']


class Contact(models.Model):
    name = models.CharField(max_length=150)
    email = models.EmailField()
    phone_number = models.CharField(max_length=20, null=True)
    subject = models.CharField(max_length=264)
    message = models.TextField()

    def __str__(self):
        return self.subject


class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.PROTECT)
    portfolio = models.URLField(blank=True, null=True)
    image = models.ImageField(upload_to='users/', default="users/no_avatar.png")

    def __str__(self):
        return self.user.username

    class Meta:
        db_table = u'userprofileinfo'
    

customer/forms.py
from django import forms
from customer.models import KhachHang

class FormDangNhap:
    ten_dang_nhap = forms.CharField(max_length=100)
    mat_khau = forms.CharField(max_length=20)


class FormDangKy(forms.ModelForm):
    ho = forms.CharField(max_length=264, label='Họ', widget=forms.TextInput(attrs={
        "class": "form-control", "placeholder": "Họ",
    }))
    ten = forms.CharField(max_length=264, label='Tên', widget=forms.TextInput(attrs={
        "class": "form-control", "placeholder": "Tên",
    }))
    email = forms.EmailField(label='Email', widget=forms.TextInput(attrs={
        "class": "form-control", "placeholder": "Email",
    }))
    mat_khau = forms.CharField(label='Mật khẩu', widget=forms.PasswordInput(attrs={
        "class": "form-control", "placeholder": "Mật khẩu",
    }))
    xac_nhan_mat_khau = forms.CharField(label='Xác nhận Mật khẩu', widget=forms.PasswordInput(attrs={
        "class": "form-control", "placeholder": "Xác nhận Mật khẩu",
    }))
    dien_thoai = forms.CharField(max_length=20, label='Điện thoại', widget=forms.TextInput(attrs={
        "class": "form-control", "placeholder": "Điện thoại",
    }))
    dia_chi = forms.CharField(label='Địa chỉ', widget=forms.Textarea(attrs={
        "class": "form-control", "placeholder": "Địa chỉ", "rows": "3",
    }))

    class Meta:
        model = KhachHang
        fields = ['ho', 'ten', 'email', 'mat_khau', 'dien_thoai', 'dia_chi']


class FormDangKy2(forms.ModelForm):
    ho = forms.CharField(max_length=264, label='Họ', widget=forms.TextInput(attrs={
        "class": "form-control", "placeholder": "Họ",
    }))
    ten = forms.CharField(max_length=264, label='Tên', widget=forms.TextInput(attrs={
        "class": "form-control", "placeholder": "Tên",
    }))
    email = forms.EmailField(label='Email', widget=forms.TextInput(attrs={
        "class": "form-control", "placeholder": "Email",
    }))
    mat_khau = forms.CharField(label='Mật khẩu', widget=forms.PasswordInput(attrs={
        "class": "form-control", "placeholder": "Mật khẩu",
    }))
    xac_nhan_mat_khau = forms.CharField(label='Xác nhận Mật khẩu', widget=forms.PasswordInput(attrs={
        "class": "form-control", "placeholder": "Xác nhận Mật khẩu",
    }))
    dien_thoai = forms.CharField(max_length=20, label='Điện thoại', widget=forms.TextInput(attrs={
        "class": "form-control", "placeholder": "Điện thoại",
    }))
    dia_chi = forms.CharField(label='Địa chỉ', widget=forms.Textarea(attrs={
        "class": "form-control", "placeholder": "Địa chỉ", "rows": "3",
    }))
    tinh_tp = forms.CharField(label='Tỉnh/TP', widget=forms.Select(attrs={
        "class": "form-control",
    }))
    quan_huyen = forms.CharField(label='Quận/Huyện', widget=forms.Select(attrs={
        "class": "form-control",
    }))
    phuong_xa = forms.CharField(label='Phường/Xã', widget=forms.Select(attrs={
        "class": "form-control",
    }))

    class Meta:
        model = KhachHang
        fields = ['ho', 'ten', 'email', 'mat_khau', 'dien_thoai', 'dia_chi']


class FormDoiMatKhau(forms.ModelForm):
    mat_khau_hien_tai = forms.CharField(label='Mật khẩu hiện tại', widget=forms.PasswordInput(attrs={
        "class": "form-control", "placeholder": "Mật khẩu hiện tại",
    }))
    mat_khau = forms.CharField(label='Mật khẩu mới', widget=forms.PasswordInput(attrs={
        "class": "form-control", "placeholder": "Mật khẩu mới",
    }))
    xac_nhan_mat_khau = forms.CharField(label='Xác nhận Mật khẩu', widget=forms.PasswordInput(attrs={
        "class": "form-control", "placeholder": "Xác nhận Mật khẩu",
    }))

    class Meta:
        model = KhachHang
        fields = ['mat_khau_hien_tai', 'mat_khau', 'xac_nhan_mat_khau']

store/forms.py
from django import forms
from django.contrib.auth.models import User
from store.models import UserProfileInfo


class FormUser(forms.ModelForm):
    username = forms.CharField(label='Username', widget=forms.TextInput(attrs={
        "class": "form-control", 
        "placeholder": "Username",
    }))
    email = forms.EmailField(label='Email', widget=forms.EmailInput(attrs={
        "class": "form-control", 
        "placeholder": "Email",
    }))
    password = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={
        "class": "form-control", 
        "placeholder": "Password",
    }))
    confirm_password = forms.CharField(label='Confirm Password', widget=forms.PasswordInput(attrs={
        "class": "form-control", 
        "placeholder": "Confirm Password",
    }))

    class Meta:
        model = User
        fields = ('username', 'email', 'password')


class FormUserProfileInfo(forms.ModelForm):
    portfolio = forms.URLField(label='Portfolio', required=False, widget=forms.TextInput(attrs={
        "class": "form-control", 
        "placeholder": "Portfolio",
    }))
    image = forms.ImageField(label='Image', required=False, widget=forms.FileInput(attrs={
        "class": "form-control-file"
    }))

    class Meta:
        model = UserProfileInfo
        fields = ('portfolio', 'image')
        # exclude = ('user',)

cart/views.py
from django.shortcuts import redirect, render, get_object_or_404
from cart.cart import Cart
from store.models import Product
from django.views.decorators.http import require_POST
from cart.models import Order, OrderItem


# Create your views here.
def checkout(request):
    cart = Cart(request)

    # đặt hàng
    if request.POST.get('btnDatHang'):
        khach_hang = request.session.get('s_khach_hang')
        order = Order()

        # Gán giá trị
        order.username = khach_hang['email']
        order.first_name = khach_hang['ten']
        order.last_name = khach_hang['ho']
        order.phone = khach_hang['dien_thoai']
        order.address = khach_hang['dia_chi']
        order.total = cart.get_final_total_price()
        order.save()

        for c in cart:
            OrderItem.objects.create(order=order,
                                        product=c['product'],
                                        price=c['price'],
                                        quantity=c['quantity'])

        cart.clear()

        return render(request, 'store/result.html', {
        'cart': cart,
        })

    return render(request, 'store/checkout.html', {
        'cart': cart,
    })


def cart_detail(request):
    cart = Cart(request)

    # Sử dụng mã giảm giá
    chuoi_kq = ''
    if request.POST.get('btnCoupon'):
        # Gán biến
        coupon_code = request.POST.get('coupon_code')
        if coupon_code == 'TTTH':
            cart_new = {}
            for c in cart:
                product = c['product']
                product_cart = {
                    str(product.pk): {
                        'quantity': c['quantity'], 
                        'price': str(product.price), 
                        'coupon': '0.9',
                        }
                    }
                cart_new.update(product_cart)  # Cập nhật vào dict cart_new để lưu vào session
                c['coupon'] = 0.9  # Cập nhật tỉ lệ giảm giá để giữ lại trên session

            request.session['cart'] = cart_new
        else:
            chuoi_kq = 'Mã không hợp lệ.'


    # Cập nhật giỏ hàng
    if request.POST.get('btnUpdateCart'):
        cart_new = {}
        for c in cart:
            product = c['product']
            quantity_new = int(request.POST.get('quantity_' + str(product.pk)))
            if quantity_new != 0:
                product_cart = {
                    str(product.pk): {
                        'quantity': quantity_new, 
                        'price': str(product.price), 
                        'coupon': str(c['coupon'])
                        }
                    }
                cart_new.update(product_cart)  # Cập nhật vào dict cart_new để lưu vào session
                c['quantity'] = quantity_new  # Cập nhật số lượng để giữ lại trên giao diện giỏ hàng
            else:
                cart.remove(product)

        request.session['cart'] = cart_new  # Lưu vào session

    return render(request, 'store/cart.html', {
        'cart': cart,
    })


@require_POST
def buy_now(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    if request.POST.get('quantity'):
        cart.add(product=product, quantity=int(request.POST.get('quantity')))
    return redirect('cart:cart_detail')


@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product=product)
    return redirect('cart:cart_detail')

store/templates/store/_Master.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>{% block title_tab %}{% endblock %}</title>
        <meta content="width=device-width, initial-scale=1.0" name="viewport">
        <meta content="eCommerce HTML Template Free Download" name="keywords">
        <meta content="eCommerce HTML Template Free Download" name="description">

        <!-- Favicon -->
        <link href="{% static 'store/img/favicon.ico' %}" rel="icon">

        <!-- Google Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400|Source+Code+Pro:700,900&display=swap" rel="stylesheet">

        <!-- CSS Libraries -->
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet">
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
        <link href="{% static 'store/lib/slick/slick.css' %}" rel="stylesheet">
        <link href="{% static 'store/lib/slick/slick-theme.css' %}" rel="stylesheet">

        <!-- Template Stylesheet -->
        <link href="{% static 'store/css/style.css' %}" rel="stylesheet">
        <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    </head>

    <body>
        <!-- Top bar Start -->
        <div class="top-bar">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-sm-6">
                        <i class="fa fa-envelope"></i>
                        support@email.com
                    </div>
                    <div class="col-sm-6">
                        <i class="fa fa-phone-alt"></i>
                        +012-345-6789
                    </div>
                </div>
            </div>
        </div>
        <!-- Top bar End -->
        
        <!-- Nav Bar Start -->
        <div class="nav">
            <div class="container-fluid">
                <nav class="navbar navbar-expand-md bg-dark navbar-dark">
                    <a href="#" class="navbar-brand">MENU</a>
                    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
                        <div class="navbar-nav mr-auto">
                            <a href="{% url 'store:index' %}" class="nav-item nav-link active">Trang chủ</a>
                            <a href="{% url 'store:subcategory' 0 %}" class="nav-item nav-link">Sản phẩm</a>
                            <a href="{% url 'store:contact' %}" class="nav-item nav-link">Liên hệ</a>
                        </div>
                        <div class="navbar-nav ml-auto">
                            {% if request.session.s_khach_hang %}
                                <div class="nav-item dropdown">
                                    <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">{{ request.session.s_khach_hang.ho }} {{ request.session.s_khach_hang.ten }}</a>
                                    <div class="dropdown-menu dropdown-menu-right">
                                        <a href="{% url 'customer:my_account' %}" class="dropdown-item">Tài khoản của tôi</a>
                                        <a href="{% url 'customer:logout' %}" class="dropdown-item">Đăng xuất</a>
                                    </div>
                                </div>
                            {% else %}
                                <a href="{% url 'customer:login' %}" class="nav-item nav-link active">Đăng nhập</a>
                            {% endif %}
                        </div>
                    </div>
                </nav>
            </div>
        </div>
        <!-- Nav Bar End -->      
        
        <!-- Bottom Bar Start -->
        <div class="bottom-bar">
            <div class="container-fluid">
                <div class="row align-items-center">
                    <div class="col-md-3">
                        <div class="logo">
                            <a href="{% url 'store:index' %}">
                                <img src="{% static 'store/img/logo.png' %}" alt="Logo">
                            </a>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <form method="get" action="{% url 'store:search' %}">
                            <div class="search">
                                <input type="text" name="product_name" value="{{ product_name }}" placeholder="Nhập từ khóa cần tìm...">
                                <button type="submit"><i class="fa fa-search"></i></button>
                            </div>
                        </form>
                    </div>
                    <div class="col-md-3">
                        <div class="user">
                            <!-- <a href="wishlist.html" class="btn wishlist">
                                <i class="fa fa-heart"></i>
                                <span>(0)</span>
                            </a> -->
                            <a href="{% url 'cart:cart_detail' %}" class="btn cart">
                                <i class="fa fa-shopping-cart"></i>
                                <span>({{ cart|length }})</span>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Bottom Bar End -->       
        
        <!-- Main Content -->
        {% block main_content %}{% endblock %}
        <!-- End Main Content -->       
        
        <!-- Footer Start -->
        <div class="footer">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-3 col-md-6">
                        <div class="footer-widget">
                            <h2>Get in Touch</h2>
                            <div class="contact-info">
                                <p><i class="fa fa-map-marker"></i>123 E Store, Los Angeles, USA</p>
                                <p><i class="fa fa-envelope"></i>email@example.com</p>
                                <p><i class="fa fa-phone"></i>+123-456-7890</p>
                            </div>
                        </div>
                    </div>
                    
                    <div class="col-lg-3 col-md-6">
                        <div class="footer-widget">
                            <h2>Follow Us</h2>
                            <div class="contact-info">
                                <div class="social">
                                    <a href=""><i class="fab fa-twitter"></i></a>
                                    <a href=""><i class="fab fa-facebook-f"></i></a>
                                    <a href=""><i class="fab fa-linkedin-in"></i></a>
                                    <a href=""><i class="fab fa-instagram"></i></a>
                                    <a href=""><i class="fab fa-youtube"></i></a>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="col-lg-3 col-md-6">
                        <div class="footer-widget">
                            <h2>Company Info</h2>
                            <ul>
                                <li><a href="#">About Us</a></li>
                                <li><a href="#">Privacy Policy</a></li>
                                <li><a href="#">Terms & Condition</a></li>
                            </ul>
                        </div>
                    </div>

                    <div class="col-lg-3 col-md-6">
                        <div class="footer-widget">
                            <h2>Purchase Info</h2>
                            <ul>
                                <li><a href="#">Pyament Policy</a></li>
                                <li><a href="#">Shipping Policy</a></li>
                                <li><a href="#">Return Policy</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                
                <div class="row payment align-items-center">
                    <div class="col-md-6">
                        <div class="payment-method">
                            <h2>We Accept:</h2>
                            <img src="img/payment-method.png" alt="Payment Method" />
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="payment-security">
                            <h2>Secured By:</h2>
                            <img src="img/godaddy.svg" alt="Payment Security" />
                            <img src="img/norton.svg" alt="Payment Security" />
                            <img src="img/ssl.svg" alt="Payment Security" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Footer End -->
        
        <!-- Footer Bottom Start -->
        <div class="footer-bottom">
            <div class="container">
                <div class="row">
                    <div class="col-md-6 copyright">
                        <p>Copyright &copy; <a href="https://htmlcodex.com">HTML Codex</a>. All Rights Reserved</p>
                    </div>

                    <div class="col-md-6 template-by">
                        <p>Template By <a href="https://htmlcodex.com">HTML Codex</a></p>
                    </div>
                </div>
            </div>
        </div>
        <!-- Footer Bottom End -->       
        
        <!-- Back to Top -->
        <a href="#" class="back-to-top"><i class="fa fa-chevron-up"></i></a>
        
        <!-- JavaScript Libraries -->
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
        <script src="{% static 'store/lib/easing/easing.min.js' %}"></script>
        <script src="{% static 'store/lib/slick/slick.min.js' %}"></script>
        
        <!-- Template Javascript -->
        <script src="{% static 'store/js/main.js' %}"></script>
    </body>
</html>

store/templates/store/my-account.html
{% extends 'store/_Master.html' %}
{% load static %}
{% load humanize %}

{% block main_content %}
        
    <!-- Breadcrumb Start -->
    <div class="breadcrumb-wrap">
        <div class="container-fluid">
            <ul class="breadcrumb">
                <li class="breadcrumb-item"><a href="{% url 'store:index' %}">Trang chủ</a></li>
                <li class="breadcrumb-item active">Tài khoản của tôi</li>
            </ul>
        </div>
    </div>
    <!-- Breadcrumb End -->
    
    <!-- My Account Start -->
    <div class="my-account">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-3">
                    <div class="nav flex-column nav-pills" role="tablist" aria-orientation="vertical">
                        <a class="nav-link active" id="account-nav" data-toggle="pill" href="#account-tab" role="tab"><i class="fa fa-user"></i>Tài khoản của tôi</a>
                        <a class="nav-link" id="orders-nav" data-toggle="pill" href="#orders-tab" role="tab"><i class="fa fa-shopping-bag"></i>Orders</a>
                        <a class="nav-link" href="{% url 'customer:logout' %}"><i class="fa fa-sign-out-alt"></i>Đăng xuất</a>
                    </div> 
                </div>
                <div class="col-md-9">
                    <div class="tab-content">
                        <div class="tab-pane fade" id="orders-tab" role="tabpanel" aria-labelledby="orders-nav">
                            <div class="table-responsive">
                                <table class="table table-bordered">
                                    <thead class="thead-dark">
                                        <tr>
                                            <th>No</th>
                                            <th>Product</th>
                                            <th>Date</th>
                                            <th>Price</th>
                                            <th>Status</th>
                                            <th>Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td>1</td>
                                            <td>Product Name</td>
                                            <td>01 Jan 2020</td>
                                            <td>$99</td>
                                            <td>Approved</td>
                                            <td><button class="btn">View</button></td>
                                        </tr>
                                        <tr>
                                            <td>2</td>
                                            <td>Product Name</td>
                                            <td>01 Jan 2020</td>
                                            <td>$99</td>
                                            <td>Approved</td>
                                            <td><button class="btn">View</button></td>
                                        </tr>
                                        <tr>
                                            <td>3</td>
                                            <td>Product Name</td>
                                            <td>01 Jan 2020</td>
                                            <td>$99</td>
                                            <td>Approved</td>
                                            <td><button class="btn">View</button></td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        <div class="tab-pane fade show active" id="account-tab" role="tabpanel" aria-labelledby="account-nav">
                            <h4>Thông tin tài khoản</h4>
                            <form method="post">
                                <div class="row">
                                    {% csrf_token %}
                                    <div class="col-md-6">
                                        <input class="form-control" name="ho" type="text" placeholder="Họ" value="{{ request.session.s_khach_hang.ho }}">
                                    </div>
                                    <div class="col-md-6">
                                        <input class="form-control" name="ten" type="text" placeholder="Tên" value="{{ request.session.s_khach_hang.ten }}">
                                    </div>
                                    <div class="col-md-6">
                                        <input class="form-control" name="dien_thoai" type="text" placeholder="Điện thoại" value="{{ request.session.s_khach_hang.dien_thoai }}">
                                    </div>
                                    <div class="col-md-6">
                                        <input class="form-control" name="email" disabled type="text" placeholder="Email" value="{{ request.session.s_khach_hang.email }}">
                                    </div>
                                    <div class="col-md-12">
                                        <input class="form-control" name="dia_chi" type="text" placeholder="Địa chỉ" value="{{ request.session.s_khach_hang.dia_chi }}">
                                    </div>
                                    <div class="col-md-12">
                                        <button class="btn" type="submit" name="btnCapNhat" value="Cập nhật tài khoản">Cập nhật tài khoản</button>
                                        <br><br>
                                    </div>
                                </div>
                            </form>
                            <h4>Đổi mật khẩu</h4>
                            <form method="post">
                                {% csrf_token %}
                                <div class="row">
                                    <div class="col-md-12">
                                        {{ form.mat_khau_hien_tai }}
                                    </div>
                                    <div class="col-md-6">
                                        {{ form.mat_khau }}
                                    </div>
                                    <div class="col-md-6">
                                        {{ form.xac_nhan_mat_khau }}
                                    </div>
                                    <div class="col-md-12">
                                        <button class="btn" type="submit" name="btnChangePass" value="Đổi mật khẩu">Đổi mật khẩu</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- My Account End -->
{% endblock %}